baseurl = "/"
languageCode = "en-us"
title = "Datalocution"
theme = "beautifulhugo"
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/seamus-mckinsey"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/seamus_mckinsey"

[Params]
    description = "Musings about words and data."
    subtitle = "Words about data"
    # options for highlight.js (version, additional languages, and theme)
    useHLJS = true
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"
    logo = "img/avatar-icon.png" # Expecting square dimensions
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true
    readingTime = true
    wordCount = true
    socialShare = true
    showRelatedPosts = true

[Author]
  name = "Seamus McKinsey"
  website = "datalocution.netlify.com"
  github = "seamus-mckinsey"
  twitter = "seamus_mckinsey"
  linkedin = "seamus-mckinsey"

